#pragma once

#include <string>
#include <vector>

#include "glgame2d/Renderer.hpp"


namespace glgame2d {


class Tilemap
{
private:
    using TileGID = int;

    struct Tileset {
        Tileset(TileGID firstgid, const std::string& image, int columns,
            int imagewidth, int imageheight, int tilecount)
            : texture{ image.c_str() },
            firstgid{ firstgid },
            image{ image },
            columns{ columns }, rows{ imageheight / (imagewidth / columns) },
            imagewidth{ imagewidth }, imageheight{ imageheight },
            tilecount{ tilecount }
        {
        }

        Texture texture;
        TileGID firstgid;
        std::string image;
        int columns, rows;
        int imagewidth, imageheight;
        int tilecount;
    };

public:
    /**
     * @brief Construct a new Tilemap object by loading a tilemap created with Tiled Map Editor.
     * 
     * @param tilemapPath Path to the JSON tilemap file generated by Tiled
     */
    Tilemap(const char* tilemapPath);

    /**
     * @brief Render the tilemap to the screen.
     * 
     * @param renderer Renderer to use for rendering
     */
    void render(const Renderer& renderer) const;
    
private:
    const Tileset& getTilesetByGID(TileGID gid) const;
    void renderTileFromTileset(
        const Renderer& renderer, const Tileset& tileset,
        const glm::vec4& uvRect, const glm::vec2& position) const;

private:
    struct {
        int width, height;
        int tileWidth, tileHeight;
    } m_MapInfo;
    std::vector<Tileset> m_Tilesets;
    std::vector<std::vector<TileGID>> m_Layers;
};


} // namespace glgame2d
